import ProjectsPage from '@/components/ProjectsPage/ProjectsPage';
import React from 'react'
export const metadata = {
  title: "Portofilio | Projects page",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <ProjectsPage />
  </>
}

export default page