import Contact from '@/components/Contact/Contact'
import React from 'react'
export const metadata = {
    title: "Portofilio | Contact page",
    description: "Generated by create next app",
  };
const page = () => {
  return <>
  <Contact />
  </>
}

export default page