import NotFoundPage from "@/components/NotfoundPage/NotfoundPage";


export const metadata = {
  title: "Portofilio | Error Not Found page",
  description: "Generated by create next app",
};
const Notfound = () => {
  return (
    <>
      <NotFoundPage />
    </>
  );
};

export default Notfound;
