import Cv from '@/components/Cv/Cv';
import React from 'react'
export const metadata = {
    title: "Portofilio | My Resume",
    description: "Generated by create next app",
  };
 const page = () => {
  return <>
  <Cv />
  </>


}
export default page;
